// use module alias
require('module-alias/register');

// Make sure we require all places there table is registered to TableSpace
// overwise migration won't be appended
require('../openland-module-hyperlog/Events');
require('./startExporters');

import { migrations } from './migrations';
import { TableSpace } from './TableSpace';
import { buildMigration } from './Migration';
import { appendFileSync } from 'fs';

for (let table of TableSpace.all()) {
    if (migrations.every(a => a.name !== `AUTOGENERATED-${table.name}-create`)) {
        let migration = buildMigration(table);
        appendFileSync('./packages/openland-module-clickhouse/migrations.ts', migration);
    }
}
