image: node:8.9.4

pipelines:
  branches:
    master: 
      - step:
          name: Test & Build
          caches:
            - node
          script:
            - yarn install
            - yarn build
            - yarn test
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker build -t openland/server:v${BITBUCKET_BUILD_NUMBER} .
            - docker push openland/server:v${BITBUCKET_BUILD_NUMBER}
      - step:
          name: Deploy to Staging
          deployment: staging
          script:
            - source ./scripts/deploy_prepare.sh
            - ./kubectl set image deployment/statecraft-server-staging statecraft-server-staging=index.docker.io/openland/server:v${BITBUCKET_BUILD_NUMBER}
            - ./kubectl rollout status deployments statecraft-server-staging || true
      - step:
          name: Deploy to Production
          deployment: production
          trigger: manual
          script:
            - source ./scripts/deploy_prepare.sh
            - ./kubectl set image deployment/statecraft-server statecraft-server=index.docker.io/openland/server:v${BITBUCKET_BUILD_NUMBER}
            - ./kubectl rollout status deployments statecraft-server || true
options:
  docker: true
