pipelines:
  default:
    - step:
        script:
          - docker build .
        services:
          - docker
    - step:
        name: Deploy
        trigger: manual
        script:
          - echo "hi!"