version: '3'
services:
  nats:
    image: openland/nats:v1
    restart: always
    environment:
      NATS_USER: natsuser
      NATS_PASSWORD: natspassword
    ports:
      - "127.0.0.1:4222:4222"
  mediakitchen:
    image: openland/mediakitchen:v4
    restart: always
    environment:
      MEDIAKITCHEN_NATS: "nats://nats:4222"
      MEDIAKITCHEN_MIN_PORT: "11000"
      MEDIAKITCHEN_MAX_PORT: "11021"
      MEDIAKITCHEN_WORKERS: "1"
      MEDIAKITCHEN_LOG_LEVEL: "debug"
      MEDIAKITCHEN_LOG_TAGS: "info,rtp,rbe,dtls,rtcp"
      DEBUG: "mediasoup:*"
    ports:
      - "127.0.0.1:3478:3478"
      - "127.0.0.1:11000:11000"
      - "127.0.0.1:11001:11001"
      - "127.0.0.1:11002:11002"
      - "127.0.0.1:11003:11003"
      - "127.0.0.1:11004:11004"
      - "127.0.0.1:11005:11005"
      - "127.0.0.1:11006:11006"
      - "127.0.0.1:11007:11007"
      - "127.0.0.1:11008:11008"
      - "127.0.0.1:11010:11010"
      - "127.0.0.1:11011:11011"
      - "127.0.0.1:11012:11012"
      - "127.0.0.1:11013:11013"
      - "127.0.0.1:11014:11014"
      - "127.0.0.1:11015:11015"
      - "127.0.0.1:11016:11016"
      - "127.0.0.1:11017:11017"
      - "127.0.0.1:11018:11018"
      - "127.0.0.1:11019:11019"
      - "127.0.0.1:11020:11020"
      - "127.0.0.1:11021:11021"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    restart: always
    environment:
      - cluster.name=testing-cluster
      - "cluster.routing.allocation.disk.watermark.high=99%"
      - "cluster.routing.allocation.disk.watermark.flood_stage=99%"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.data/elastic:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
  clickhouse:
    image: yandex/clickhouse-server:19.16.19.85
    restart: always
    ports: 
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9001:9000"
    volumes:
      - ./.data/clickhouse:/var/lib/clickhouse