
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t statecraft/statecraft-server:latest .
  publish:
     steps:
      - run: docker push statecraft/statecraft-server:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - publish:
          requires:
            build