version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test
      # - run: yarn install --production --ignore-scripts --prefer-offline
      - persist_to_workspace:
          root: /build
          paths:
            - './node_modules'
            - './build'
            - './package.json'
            - './Dockerfile'
  docker:
    machine: true
    steps:
      - attach_workspace:
          at: ./dist
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build -t statecraft/statecraft-server:v${CIRCLE_BUILD_NUM} -t statecraft/statecraft-server:git-${CIRCLE_SHA1} ./dist/.
      - run: docker push statecraft/statecraft-server:v${CIRCLE_BUILD_NUM}
      - run: docker push statecraft/statecraft-server:git-${CIRCLE_SHA1}
  staging:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: echo ${KUBE_ACCOUNT} > ${HOME}/gcp-key.json
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project statecraft-188615
      - run: gcloud --quiet config set compute/zone us-west1-a
      - run: gcloud --quiet container clusters get-credentials statekube
      - run: kubectl set image deployment/statecraft-server-staging statecraft-server-staging=index.docker.io/statecraft/statecraft-server:git-${CIRCLE_SHA1}
      - run: kubectl rollout status deployments statecraft-server-staging || true

workflows:
  version: 2
  build:
    jobs:
      - build
      - docker:
          requires:
            - build
      - staging:
          requires:
            - docker
