// THIS FILE IS AUTOGENERATED! DO NOT TRY TO EDIT!
import { FEntity } from 'foundation-orm/FEntity';
import { FNamespace } from 'foundation-orm/FNamespace';
import { FEntityFactory } from 'foundation-orm/FEntityFactory';
import { FConnection } from 'foundation-orm/FConnection';
import { FContext } from 'foundation-orm/FContext';

export interface OnlineShape {
    lastSeen: number;
}

export class Online extends FEntity {
    get uid() { return this._value.uid; }
    get lastSeen() {
        return this._value.lastSeen;
    }
    set lastSeen(value: number) {
        this._checkIsWritable();
        if (value ===  this._value.lastSeen) { return; }
        this._value.lastSeen = value;
        this._markDirty();
    }
}

export class OnlineFactory extends FEntityFactory<Online> {
    constructor(connection: FConnection) {
        super(connection, new FNamespace('online'));
    }
    async findById(uid: number) {
        return await this._findById([uid]);
    }
    protected _createEntity(context: FContext, namespace: FNamespace, id: (string | number)[], value: any) {
        return new Online(context, namespace, id, value);
    }
}
export interface PresenceShape {
    lastSeen: number;
    lastSeenTimeout: number;
    platform: string;
}

export class Presence extends FEntity {
    get uid() { return this._value.uid; }
    get tid() { return this._value.tid; }
    get lastSeen() {
        return this._value.lastSeen;
    }
    set lastSeen(value: number) {
        this._checkIsWritable();
        if (value ===  this._value.lastSeen) { return; }
        this._value.lastSeen = value;
        this._markDirty();
    }
    get lastSeenTimeout() {
        return this._value.lastSeenTimeout;
    }
    set lastSeenTimeout(value: number) {
        this._checkIsWritable();
        if (value ===  this._value.lastSeenTimeout) { return; }
        this._value.lastSeenTimeout = value;
        this._markDirty();
    }
    get platform() {
        return this._value.platform;
    }
    set platform(value: string) {
        this._checkIsWritable();
        if (value ===  this._value.platform) { return; }
        this._value.platform = value;
        this._markDirty();
    }
}

export class PresenceFactory extends FEntityFactory<Presence> {
    constructor(connection: FConnection) {
        super(connection, new FNamespace('presence'));
    }
    async findById(uid: number, tid: string) {
        return await this._findById([uid, tid]);
    }
    protected _createEntity(context: FContext, namespace: FNamespace, id: (string | number)[], value: any) {
        return new Presence(context, namespace, id, value);
    }
}
export interface CounterShape {
    value: number;
}

export class Counter extends FEntity {
    get name() { return this._value.name; }
    get value() {
        return this._value.value;
    }
    set value(value: number) {
        this._checkIsWritable();
        if (value ===  this._value.value) { return; }
        this._value.value = value;
        this._markDirty();
    }
}

export class CounterFactory extends FEntityFactory<Counter> {
    constructor(connection: FConnection) {
        super(connection, new FNamespace('counter'));
    }
    async findById(name: string) {
        return await this._findById([name]);
    }
    protected _createEntity(context: FContext, namespace: FNamespace, id: (string | number)[], value: any) {
        return new Counter(context, namespace, id, value);
    }
}
