apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mixpanel-proxy
  name: mixpanel-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mixpanel-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mixpanel-proxy
    spec:
      containers:
      - image: index.docker.io/openland/mixpanel:latest
        imagePullPolicy: IfNotPresent
        name: mixpanel
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
      imagePullSecrets:
      - name: openland-docker
      restartPolicy: Always