apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mediakitchen
  labels:
    app: mediakitchen
spec:
  selector:
    matchLabels:
      app: mediakitchen
  template:
    metadata:
      labels:
        app: mediakitchen
    spec:
      hostNetwork: true
      containers:
        - name: mediakitchen
          image: openland/mediakitchen:v6
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: MEDIAKITCHEN_DC
              value: europe-west2
            - name: MEDIAKITCHEN_DETECT_IP
              value: "true"
            - name: DEBUG
              value: '*'
            - name: MEDIAKITCHEN_NATS
              value: nats://nats.services.openlandservers.com:4222              