apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openland-server-api
  name: openland-server-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openland-server-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openland-server-api
    spec:
      containers:
      - env:
        - name: SERVER_ROLES
          value: api
        - name: OPENLAND_CONFIG
          value: /secrets/openland/config.json
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          value: "6832"
        image: index.docker.io/openland/server:<version>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: openland-server
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status
            port: 9000
        volumeMounts:
        - mountPath: /secrets/openland
          name: openland-config
          readOnly: true
      imagePullSecrets:
      - name: openland-docker
      restartPolicy: Always
      volumes:
      - name: openland-config
        secret:
          defaultMode: 420
          secretName: openland-config