apiVersion: v1
kind: Service
metadata:
  name: openland-server-admin-nodeport
spec:
  type: NodePort
  selector:
    app: openland-server-admin
  ports:
    - protocol: TCP
      port: 8319
      targetPort: 8319
      nodePort: 30009