apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openland-server-delivery
  name: openland-server-delivery
spec:
  replicas: 6
  selector:
    matchLabels:
      app: openland-server-delivery
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openland-server-delivery
    spec:
      containers:
      - env:
        - name: SERVER_ROLES
          value: delivery
        - name: OPENLAND_CONFIG
          value: /secrets/openland/config.json
        image: index.docker.io/openland/server:<version>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: openland-server
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 9000
        volumeMounts:
        - mountPath: /secrets/openland
          name: openland-config
          readOnly: true
      imagePullSecrets:
      - name: openland-docker
      restartPolicy: Always
      volumes:
      - name: openland-config
        secret:
          defaultMode: 420
          secretName: openland-config