apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: screenshotter
  name: screenshotter
spec:
  replicas: 12
  selector:
    matchLabels:
      app: screenshotter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: screenshotter
    spec:
      containers:
        - name: screenshotter
          image: index.docker.io/openland/chrome-screenshot:v7.3.1
          resources: {}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
      imagePullSecrets:
        - name: openland-docker
