import { EventsMediator } from './mediators/EventsMediator';
import { MessagesEventsRepository } from './repositories/MessagesEventsRepository';
import { container } from 'openland-modules/Modules.container';
import { MessagingModule } from './MessagingModule';
import { UserStateRepository } from './repositories/UserStateRepository';
import { DeliveryRepository } from './repositories/DeliveryRepository';
import { MessagesRepository } from './repositories/MessagesRepository';
import { RoomRepository } from './repositories/RoomRepository';
import { MessagingMediator } from './mediators/MessagingMediator';
import { AugmentationMediator } from './mediators/AugmentationMediator';
import { DeliveryMediator } from './mediators/DeliveryMediator';
import { RoomMediator } from './mediators/RoomMediator';
import { FixerRepository } from './repositories/Fixer';
import { ChatMetricsRepository } from './repositories/ChatMetricsRepository';
import { NeedNotificationDeliveryRepository } from './repositories/NeedNotificationDeliveryRepository';
import { UserDialogsRepository } from './repositories/UserDialogsRepository';
import { MentionNotificationsMediator } from './mediators/MentionNotificationsMediator';
import { PremiumChatMediator } from './mediators/PremiumChatMediator';
import { PremiumChatRepository } from './repositories/PremiumChatRepository';
import { DonationsMediator } from './mediators/DonationsMediator';
import { PrecalculatedCounterProvider } from './counters/PrecalculatedCounterProvider';
import { UserReadSeqsDirectory } from './repositories/UserReadSeqsDirectory';
import { ChatsMembersListDirectory } from './repositories/ChatsMembersListDirectory';
import { DialogListSettingsRepository } from './repositories/DialogListSettingsRepository';
import { DialogListSettingsMediator } from './mediators/DialogListSettingsMediator';

export function loadMessagingModule() {
    container.bind(MessagingModule).toSelf().inSingletonScope();
    container.bind('UserStateRepository').to(UserStateRepository).inSingletonScope();
    container.bind('DeliveryRepository').to(DeliveryRepository).inSingletonScope();
    container.bind('MessagesRepository').to(MessagesRepository).inSingletonScope();
    container.bind('RoomRepository').to(RoomRepository).inSingletonScope();
    container.bind('MessagingMediator').to(MessagingMediator).inSingletonScope();
    container.bind('PremiumChatRepository').to(PremiumChatRepository).inSingletonScope();
    container.bind('PremiumChatMediator').to(PremiumChatMediator).inSingletonScope();
    container.bind('AugmentationMediator').to(AugmentationMediator).inSingletonScope();
    container.bind('DeliveryMediator').to(DeliveryMediator).inSingletonScope();
    container.bind('RoomMediator').to(RoomMediator).inSingletonScope();
    container.bind('FixerRepository').to(FixerRepository).inSingletonScope();
    container.bind('ChatMetricsRepository').to(ChatMetricsRepository).inSingletonScope();
    container.bind('NeedNotificationDeliveryRepository').to(NeedNotificationDeliveryRepository).inSingletonScope();
    container.bind('UserDialogsRepository').to(UserDialogsRepository).inSingletonScope();
    container.bind('MentionNotificationsMediator').to(MentionNotificationsMediator).inSingletonScope();
    container.bind('DonationsMediator').to(DonationsMediator).inSingletonScope();
    container.bind('PrecalculatedCounterProvider').to(PrecalculatedCounterProvider).inSingletonScope();
    container.bind('UserReadSeqsDirectory').to(UserReadSeqsDirectory).inSingletonScope();
    container.bind('ChatsMembersListDirectory').to(ChatsMembersListDirectory).inSingletonScope();
    container.bind('MessagesEventsRepository').to(MessagesEventsRepository).inSingletonScope();
    container.bind('MessagingEventsMediator').to(EventsMediator).inSingletonScope();

    container.bind('DialogListSettingsRepository').to(DialogListSettingsRepository).inSingletonScope();
    container.bind('DialogListSettingsMediator').to(DialogListSettingsMediator).inSingletonScope();
}