// THIS FILE IS AUTOGENERATED! DO NOT TRY TO EDIT!
// @ts-ignore
import { EntitiesBase } from 'foundation-orm/EntitiesBase';
// @ts-ignore
import { Subspace, Directory, Tuple } from '@openland/foundationdb';
// @ts-ignore
import { FEntity, FEntityOptions } from 'foundation-orm/FEntity';
// @ts-ignore
import { FEntitySchema } from 'foundation-orm/FEntitySchema';
// @ts-ignore
import { FEntityIndex } from 'foundation-orm/FEntityIndex';
// @ts-ignore
import { FEntityFactory } from 'foundation-orm/FEntityFactory';
// @ts-ignore
import { FConnection } from 'foundation-orm/FConnection';
// @ts-ignore
import { validators } from 'foundation-orm/utils/validators';
// @ts-ignore
import { EntityLayer } from 'foundation-orm/EntityLayer';
// @ts-ignore
import { Context } from '@openland/context';
// @ts-ignore
import { json, jField, jNumber, jString, jBool, jVec, jEnum, jEnumString } from 'openland-utils/jsonSchema';

export interface MessageShape {
    cid: number;
    uid: number;
    repeatKey?: string| null;
    text?: string| null;
    replyMessages?: (number)[]| null;
    serviceMetadata?: any| null;
    reactions?: ({ userId: number, reaction: string, })[]| null;
    edited?: boolean| null;
    isMuted: boolean;
    isService: boolean;
    deleted?: boolean| null;
    spans?: ({ type: 'user_mention', offset: number, length: number, user: number, } | { type: 'multi_user_mention', offset: number, length: number, users: (number)[], } | { type: 'room_mention', offset: number, length: number, room: number, } | { type: 'link', offset: number, length: number, url: string, } | { type: 'bold_text', offset: number, length: number, } | { type: 'italic_text', offset: number, length: number, } | { type: 'irony_text', offset: number, length: number, } | { type: 'inline_code_text', offset: number, length: number, } | { type: 'code_block_text', offset: number, length: number, } | { type: 'insane_text', offset: number, length: number, } | { type: 'loud_text', offset: number, length: number, } | { type: 'rotating_text', offset: number, length: number, } | { type: 'date_text', offset: number, length: number, date: number, } | { type: 'all_mention', offset: number, length: number, })[]| null;
    attachmentsModern?: ({ type: 'file_attachment', fileId: string, filePreview: string | null, fileMetadata: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, id: string, } | { type: 'rich_attachment', title: string | null, subTitle: string | null, titleLink: string | null, text: string | null, icon: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, image: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, iconInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, imageInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, titleLinkHostname: string | null, keyboard: { buttons: (({ title: string, style: 'DEFAULT' | 'LIGHT', url: string | null, })[])[], } | null, id: string, })[]| null;
    fileId?: string| null;
    fileMetadata?: { isStored: boolean | undefined, isImage: boolean | null, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, }| null;
    filePreview?: string| null;
    augmentation?: any| null;
    mentions?: any| null;
    attachments?: any| null;
    buttons?: any| null;
    type?: string| null;
    title?: string| null;
    postType?: string| null;
    complexMentions?: any| null;
}

export class Message extends FEntity {
    readonly entityName: 'Message' = 'Message';
    get id(): number { return this._value.id; }
    get cid(): number {
        return this._value.cid;
    }
    set cid(value: number) {
        this._checkIsWritable();
        if (value === this._value.cid) { return; }
        this._value.cid = value;
        this.markDirty();
    }
    get uid(): number {
        return this._value.uid;
    }
    set uid(value: number) {
        this._checkIsWritable();
        if (value === this._value.uid) { return; }
        this._value.uid = value;
        this.markDirty();
    }
    get repeatKey(): string | null {
        let res = this._value.repeatKey;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set repeatKey(value: string | null) {
        this._checkIsWritable();
        if (value === this._value.repeatKey) { return; }
        this._value.repeatKey = value;
        this.markDirty();
    }
    get text(): string | null {
        let res = this._value.text;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set text(value: string | null) {
        this._checkIsWritable();
        if (value === this._value.text) { return; }
        this._value.text = value;
        this.markDirty();
    }
    get replyMessages(): (number)[] | null {
        let res = this._value.replyMessages;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set replyMessages(value: (number)[] | null) {
        this._checkIsWritable();
        if (value === this._value.replyMessages) { return; }
        this._value.replyMessages = value;
        this.markDirty();
    }
    get serviceMetadata(): any | null {
        let res = this._value.serviceMetadata;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set serviceMetadata(value: any | null) {
        this._checkIsWritable();
        if (value === this._value.serviceMetadata) { return; }
        this._value.serviceMetadata = value;
        this.markDirty();
    }
    get reactions(): ({ userId: number, reaction: string, })[] | null {
        let res = this._value.reactions;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set reactions(value: ({ userId: number, reaction: string, })[] | null) {
        this._checkIsWritable();
        if (value === this._value.reactions) { return; }
        this._value.reactions = value;
        this.markDirty();
    }
    get edited(): boolean | null {
        let res = this._value.edited;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set edited(value: boolean | null) {
        this._checkIsWritable();
        if (value === this._value.edited) { return; }
        this._value.edited = value;
        this.markDirty();
    }
    get isMuted(): boolean {
        return this._value.isMuted;
    }
    set isMuted(value: boolean) {
        this._checkIsWritable();
        if (value === this._value.isMuted) { return; }
        this._value.isMuted = value;
        this.markDirty();
    }
    get isService(): boolean {
        return this._value.isService;
    }
    set isService(value: boolean) {
        this._checkIsWritable();
        if (value === this._value.isService) { return; }
        this._value.isService = value;
        this.markDirty();
    }
    get deleted(): boolean | null {
        let res = this._value.deleted;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set deleted(value: boolean | null) {
        this._checkIsWritable();
        if (value === this._value.deleted) { return; }
        this._value.deleted = value;
        this.markDirty();
    }
    get spans(): ({ type: 'user_mention', offset: number, length: number, user: number, } | { type: 'multi_user_mention', offset: number, length: number, users: (number)[], } | { type: 'room_mention', offset: number, length: number, room: number, } | { type: 'link', offset: number, length: number, url: string, } | { type: 'bold_text', offset: number, length: number, } | { type: 'italic_text', offset: number, length: number, } | { type: 'irony_text', offset: number, length: number, } | { type: 'inline_code_text', offset: number, length: number, } | { type: 'code_block_text', offset: number, length: number, } | { type: 'insane_text', offset: number, length: number, } | { type: 'loud_text', offset: number, length: number, } | { type: 'rotating_text', offset: number, length: number, } | { type: 'date_text', offset: number, length: number, date: number, } | { type: 'all_mention', offset: number, length: number, })[] | null {
        let res = this._value.spans;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set spans(value: ({ type: 'user_mention', offset: number, length: number, user: number, } | { type: 'multi_user_mention', offset: number, length: number, users: (number)[], } | { type: 'room_mention', offset: number, length: number, room: number, } | { type: 'link', offset: number, length: number, url: string, } | { type: 'bold_text', offset: number, length: number, } | { type: 'italic_text', offset: number, length: number, } | { type: 'irony_text', offset: number, length: number, } | { type: 'inline_code_text', offset: number, length: number, } | { type: 'code_block_text', offset: number, length: number, } | { type: 'insane_text', offset: number, length: number, } | { type: 'loud_text', offset: number, length: number, } | { type: 'rotating_text', offset: number, length: number, } | { type: 'date_text', offset: number, length: number, date: number, } | { type: 'all_mention', offset: number, length: number, })[] | null) {
        this._checkIsWritable();
        if (value === this._value.spans) { return; }
        this._value.spans = value;
        this.markDirty();
    }
    get attachmentsModern(): ({ type: 'file_attachment', fileId: string, filePreview: string | null, fileMetadata: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, id: string, } | { type: 'rich_attachment', title: string | null, subTitle: string | null, titleLink: string | null, text: string | null, icon: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, image: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, iconInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, imageInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, titleLinkHostname: string | null, keyboard: { buttons: (({ title: string, style: 'DEFAULT' | 'LIGHT', url: string | null, })[])[], } | null, id: string, })[] | null {
        let res = this._value.attachmentsModern;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set attachmentsModern(value: ({ type: 'file_attachment', fileId: string, filePreview: string | null, fileMetadata: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, id: string, } | { type: 'rich_attachment', title: string | null, subTitle: string | null, titleLink: string | null, text: string | null, icon: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, image: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, iconInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, imageInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, titleLinkHostname: string | null, keyboard: { buttons: (({ title: string, style: 'DEFAULT' | 'LIGHT', url: string | null, })[])[], } | null, id: string, })[] | null) {
        this._checkIsWritable();
        if (value === this._value.attachmentsModern) { return; }
        this._value.attachmentsModern = value;
        this.markDirty();
    }
    get fileId(): string | null {
        let res = this._value.fileId;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set fileId(value: string | null) {
        this._checkIsWritable();
        if (value === this._value.fileId) { return; }
        this._value.fileId = value;
        this.markDirty();
    }
    get fileMetadata(): { isStored: boolean | undefined, isImage: boolean | null, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null {
        let res = this._value.fileMetadata;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set fileMetadata(value: { isStored: boolean | undefined, isImage: boolean | null, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null) {
        this._checkIsWritable();
        if (value === this._value.fileMetadata) { return; }
        this._value.fileMetadata = value;
        this.markDirty();
    }
    get filePreview(): string | null {
        let res = this._value.filePreview;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set filePreview(value: string | null) {
        this._checkIsWritable();
        if (value === this._value.filePreview) { return; }
        this._value.filePreview = value;
        this.markDirty();
    }
    get augmentation(): any | null {
        let res = this._value.augmentation;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set augmentation(value: any | null) {
        this._checkIsWritable();
        if (value === this._value.augmentation) { return; }
        this._value.augmentation = value;
        this.markDirty();
    }
    get mentions(): any | null {
        let res = this._value.mentions;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set mentions(value: any | null) {
        this._checkIsWritable();
        if (value === this._value.mentions) { return; }
        this._value.mentions = value;
        this.markDirty();
    }
    get attachments(): any | null {
        let res = this._value.attachments;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set attachments(value: any | null) {
        this._checkIsWritable();
        if (value === this._value.attachments) { return; }
        this._value.attachments = value;
        this.markDirty();
    }
    get buttons(): any | null {
        let res = this._value.buttons;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set buttons(value: any | null) {
        this._checkIsWritable();
        if (value === this._value.buttons) { return; }
        this._value.buttons = value;
        this.markDirty();
    }
    get type(): string | null {
        let res = this._value.type;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set type(value: string | null) {
        this._checkIsWritable();
        if (value === this._value.type) { return; }
        this._value.type = value;
        this.markDirty();
    }
    get title(): string | null {
        let res = this._value.title;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set title(value: string | null) {
        this._checkIsWritable();
        if (value === this._value.title) { return; }
        this._value.title = value;
        this.markDirty();
    }
    get postType(): string | null {
        let res = this._value.postType;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set postType(value: string | null) {
        this._checkIsWritable();
        if (value === this._value.postType) { return; }
        this._value.postType = value;
        this.markDirty();
    }
    get complexMentions(): any | null {
        let res = this._value.complexMentions;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set complexMentions(value: any | null) {
        this._checkIsWritable();
        if (value === this._value.complexMentions) { return; }
        this._value.complexMentions = value;
        this.markDirty();
    }
}

export class MessageFactory extends FEntityFactory<Message> {
    static schema: FEntitySchema = {
        name: 'Message',
        editable: false,
        primaryKeys: [
            { name: 'id', type: 'number' },
        ],
        fields: [
            { name: 'cid', type: 'number' },
            { name: 'uid', type: 'number' },
            { name: 'repeatKey', type: 'string' },
            { name: 'text', type: 'string', secure: true },
            { name: 'replyMessages', type: 'json' },
            { name: 'serviceMetadata', type: 'json' },
            { name: 'reactions', type: 'json' },
            { name: 'edited', type: 'boolean' },
            { name: 'isMuted', type: 'boolean' },
            { name: 'isService', type: 'boolean' },
            { name: 'deleted', type: 'boolean' },
            { name: 'spans', type: 'json' },
            { name: 'attachmentsModern', type: 'json' },
            { name: 'fileId', type: 'string', secure: true },
            { name: 'fileMetadata', type: 'json', secure: true },
            { name: 'filePreview', type: 'string', secure: true },
            { name: 'augmentation', type: 'json' },
            { name: 'mentions', type: 'json' },
            { name: 'attachments', type: 'json' },
            { name: 'buttons', type: 'json' },
            { name: 'type', type: 'string' },
            { name: 'title', type: 'string' },
            { name: 'postType', type: 'string' },
            { name: 'complexMentions', type: 'json' },
        ],
        indexes: [
            { name: 'chat', type: 'range', fields: ['cid', 'id'] },
            { name: 'updated', type: 'range', fields: ['updatedAt'] },
            { name: 'repeat', type: 'unique', fields: ['uid', 'cid', 'repeatKey'] },
        ],
    };

    static async create(layer: EntityLayer) {
        let directory = await layer.resolveEntityDirectory('message');
        let config = { enableVersioning: true, enableTimestamps: true, validator: MessageFactory.validate, keyValidator: MessageFactory.validateKey, hasLiveStreams: false };
        let indexChat = new FEntityIndex(await layer.resolveEntityIndexDirectory('message', 'chat'), 'chat', ['cid', 'id'], false, (src) => !src.deleted);
        let indexUpdated = new FEntityIndex(await layer.resolveEntityIndexDirectory('message', 'updated'), 'updated', ['updatedAt'], false);
        let indexRepeat = new FEntityIndex(await layer.resolveEntityIndexDirectory('message', 'repeat'), 'repeat', ['uid', 'cid', 'repeatKey'], true, (src) => !!src.repeatKey);
        let indexes = {
            chat: indexChat,
            updated: indexUpdated,
            repeat: indexRepeat,
        };
        return new MessageFactory(layer, directory, config, indexes);
    }

    readonly indexChat: FEntityIndex;
    readonly indexUpdated: FEntityIndex;
    readonly indexRepeat: FEntityIndex;

    private static validate(src: any) {
        validators.notNull('id', src.id);
        validators.isNumber('id', src.id);
        validators.notNull('cid', src.cid);
        validators.isNumber('cid', src.cid);
        validators.notNull('uid', src.uid);
        validators.isNumber('uid', src.uid);
        validators.isString('repeatKey', src.repeatKey);
        validators.isString('text', src.text);
        validators.isJson('replyMessages', src.replyMessages, jVec(jNumber()));
        validators.isJson('reactions', src.reactions, jVec(json(() => {
            jField('userId', jNumber());
            jField('reaction', jString());
        })));
        validators.isBoolean('edited', src.edited);
        validators.notNull('isMuted', src.isMuted);
        validators.isBoolean('isMuted', src.isMuted);
        validators.notNull('isService', src.isService);
        validators.isBoolean('isService', src.isService);
        validators.isBoolean('deleted', src.deleted);
        validators.isJson('spans', src.spans, jVec(jEnum(
            json(() => {
                jField('type', jString('user_mention'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('user', jNumber());
            }), 
            json(() => {
                jField('type', jString('multi_user_mention'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('users', jVec(jNumber()));
            }), 
            json(() => {
                jField('type', jString('room_mention'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('room', jNumber());
            }), 
            json(() => {
                jField('type', jString('link'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('url', jString());
            }), 
            json(() => {
                jField('type', jString('bold_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('italic_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('irony_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('inline_code_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('code_block_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('insane_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('loud_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('rotating_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('date_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('date', jNumber());
            }), 
            json(() => {
                jField('type', jString('all_mention'));
                jField('offset', jNumber());
                jField('length', jNumber());
            })
        )));
        validators.isJson('attachmentsModern', src.attachmentsModern, jVec(jEnum(
            json(() => {
                jField('type', jString('file_attachment'));
                jField('fileId', jString());
                jField('filePreview', jString()).nullable();
                jField('fileMetadata', json(() => {
                jField('isImage', jBool());
                jField('isStored', jBool());
                jField('imageWidth', jNumber()).nullable();
                jField('imageHeight', jNumber()).nullable();
                jField('imageFormat', jString()).nullable();
                jField('mimeType', jString());
                jField('name', jString());
                jField('size', jNumber());
            })).nullable();
                jField('id', jString());
            }), 
            json(() => {
                jField('type', jString('rich_attachment'));
                jField('title', jString()).nullable();
                jField('subTitle', jString()).nullable();
                jField('titleLink', jString()).nullable();
                jField('text', jString()).nullable();
                jField('icon', json(() => {
                jField('uuid', jString());
                jField('crop', json(() => {
                jField('x', jNumber());
                jField('y', jNumber());
                jField('w', jNumber());
                jField('h', jNumber());
            })).nullable();
            })).nullable();
                jField('image', json(() => {
                jField('uuid', jString());
                jField('crop', json(() => {
                jField('x', jNumber());
                jField('y', jNumber());
                jField('w', jNumber());
                jField('h', jNumber());
            })).nullable();
            })).nullable();
                jField('iconInfo', json(() => {
                jField('isImage', jBool());
                jField('isStored', jBool());
                jField('imageWidth', jNumber()).nullable();
                jField('imageHeight', jNumber()).nullable();
                jField('imageFormat', jString()).nullable();
                jField('mimeType', jString());
                jField('name', jString());
                jField('size', jNumber());
            })).nullable();
                jField('imageInfo', json(() => {
                jField('isImage', jBool());
                jField('isStored', jBool());
                jField('imageWidth', jNumber()).nullable();
                jField('imageHeight', jNumber()).nullable();
                jField('imageFormat', jString()).nullable();
                jField('mimeType', jString());
                jField('name', jString());
                jField('size', jNumber());
            })).nullable();
                jField('titleLinkHostname', jString()).nullable();
                jField('keyboard', json(() => {
                jField('buttons', jVec(jVec(json(() => {
                jField('title', jString());
                jField('style', jEnumString('DEFAULT', 'LIGHT'));
                jField('url', jString()).nullable();
            }))));
            })).nullable();
                jField('id', jString());
            })
        )));
        validators.isString('fileId', src.fileId);
        validators.isJson('fileMetadata', src.fileMetadata, json(() => {
            jField('isStored', jBool()).undefinable();
            jField('isImage', jBool()).nullable();
            jField('imageWidth', jNumber()).nullable();
            jField('imageHeight', jNumber()).nullable();
            jField('imageFormat', jString()).nullable();
            jField('mimeType', jString());
            jField('name', jString());
            jField('size', jNumber());
        }));
        validators.isString('filePreview', src.filePreview);
        validators.isString('type', src.type);
        validators.isString('title', src.title);
        validators.isString('postType', src.postType);
    }

    private static validateKey(key: Tuple[]) {
        validators.isNumber('0', key[0]);
    }

    constructor(layer: EntityLayer, directory: Subspace, config: FEntityOptions, indexes: { chat: FEntityIndex, updated: FEntityIndex, repeat: FEntityIndex }) {
        super('Message', 'message', config, [indexes.chat, indexes.updated, indexes.repeat], layer, directory);
        this.indexChat = indexes.chat;
        this.indexUpdated = indexes.updated;
        this.indexRepeat = indexes.repeat;
    }
    extractId(rawId: any[]) {
        if (rawId.length !== 1) { throw Error('Invalid key length!'); }
        return { 'id': rawId[0] };
    }
    async findById(ctx: Context, id: number) {
        return await this._findById(ctx, [id]);
    }
    async create(ctx: Context, id: number, shape: MessageShape) {
        return await this._create(ctx, [id], { id, ...shape });
    }
    async create_UNSAFE(ctx: Context, id: number, shape: MessageShape) {
        return await this._create_UNSAFE(ctx, [id], { id, ...shape });
    }
    watch(ctx: Context, id: number) {
        return this._watch(ctx, [id]);
    }
    async allFromChatAfter(ctx: Context, cid: number, after: number) {
        return await this._findRangeAllAfter(ctx, this.indexChat.directory, [cid], after);
    }
    async rangeFromChatAfter(ctx: Context, cid: number, after: number, limit: number, reversed?: boolean) {
        return await this._findRangeAfter(ctx, this.indexChat.directory, [cid], after, limit, reversed);
    }
    async rangeFromChat(ctx: Context, cid: number, limit: number, reversed?: boolean) {
        return await this._findRange(ctx, this.indexChat.directory, [cid], limit, reversed);
    }
    async rangeFromChatWithCursor(ctx: Context, cid: number, limit: number, after?: string, reversed?: boolean) {
        return await this._findRangeWithCursor(ctx, this.indexChat.directory, [cid], limit, after, reversed);
    }
    async allFromChat(ctx: Context, cid: number) {
        return await this._findAll(ctx, this.indexChat.directory, [cid]);
    }
    createChatStream(cid: number, limit: number, after?: string) {
        return this._createStream(this.indexChat.directory, [cid], limit, after); 
    }
    async rangeFromUpdated(ctx: Context, limit: number, reversed?: boolean) {
        return await this._findRange(ctx, this.indexUpdated.directory, [], limit, reversed);
    }
    async rangeFromUpdatedWithCursor(ctx: Context, limit: number, after?: string, reversed?: boolean) {
        return await this._findRangeWithCursor(ctx, this.indexUpdated.directory, [], limit, after, reversed);
    }
    async allFromUpdated(ctx: Context, ) {
        return await this._findAll(ctx, this.indexUpdated.directory, []);
    }
    createUpdatedStream(limit: number, after?: string) {
        return this._createStream(this.indexUpdated.directory, [], limit, after); 
    }
    async findFromRepeat(ctx: Context, uid: number, cid: number, repeatKey: string) {
        return await this._findFromIndex(ctx, this.indexRepeat.directory, [uid, cid, repeatKey]);
    }
    async allFromRepeatAfter(ctx: Context, uid: number, cid: number, after: string) {
        return await this._findRangeAllAfter(ctx, this.indexRepeat.directory, [uid, cid], after);
    }
    async rangeFromRepeatAfter(ctx: Context, uid: number, cid: number, after: string, limit: number, reversed?: boolean) {
        return await this._findRangeAfter(ctx, this.indexRepeat.directory, [uid, cid], after, limit, reversed);
    }
    async rangeFromRepeat(ctx: Context, uid: number, cid: number, limit: number, reversed?: boolean) {
        return await this._findRange(ctx, this.indexRepeat.directory, [uid, cid], limit, reversed);
    }
    async rangeFromRepeatWithCursor(ctx: Context, uid: number, cid: number, limit: number, after?: string, reversed?: boolean) {
        return await this._findRangeWithCursor(ctx, this.indexRepeat.directory, [uid, cid], limit, after, reversed);
    }
    async allFromRepeat(ctx: Context, uid: number, cid: number) {
        return await this._findAll(ctx, this.indexRepeat.directory, [uid, cid]);
    }
    createRepeatStream(uid: number, cid: number, limit: number, after?: string) {
        return this._createStream(this.indexRepeat.directory, [uid, cid], limit, after); 
    }
    protected _createEntity(ctx: Context, value: any, isNew: boolean) {
        return new Message(ctx, this.layer, this.directory, [value.id], value, this.options, isNew, this.indexes, 'Message');
    }
}
export interface CommentShape {
    peerId: number;
    peerType: 'message';
    parentCommentId?: number| null;
    uid: number;
    text?: string| null;
    reactions?: ({ userId: number, reaction: string, })[]| null;
    spans?: ({ type: 'user_mention', offset: number, length: number, user: number, } | { type: 'multi_user_mention', offset: number, length: number, users: (number)[], } | { type: 'room_mention', offset: number, length: number, room: number, } | { type: 'link', offset: number, length: number, url: string, } | { type: 'bold_text', offset: number, length: number, } | { type: 'italic_text', offset: number, length: number, } | { type: 'irony_text', offset: number, length: number, } | { type: 'inline_code_text', offset: number, length: number, } | { type: 'code_block_text', offset: number, length: number, } | { type: 'insane_text', offset: number, length: number, } | { type: 'loud_text', offset: number, length: number, } | { type: 'rotating_text', offset: number, length: number, } | { type: 'date_text', offset: number, length: number, date: number, } | { type: 'all_mention', offset: number, length: number, })[]| null;
    attachments?: ({ type: 'file_attachment', fileId: string, filePreview: string | null, fileMetadata: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, id: string, } | { type: 'rich_attachment', title: string | null, subTitle: string | null, titleLink: string | null, text: string | null, icon: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, image: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, iconInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, imageInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, titleLinkHostname: string | null, keyboard: { buttons: (({ title: string, style: 'DEFAULT' | 'LIGHT', url: string | null, })[])[], } | null, id: string, })[]| null;
    deleted?: boolean| null;
    edited?: boolean| null;
    visible?: boolean| null;
}

export class Comment extends FEntity {
    readonly entityName: 'Comment' = 'Comment';
    get id(): number { return this._value.id; }
    get peerId(): number {
        return this._value.peerId;
    }
    set peerId(value: number) {
        this._checkIsWritable();
        if (value === this._value.peerId) { return; }
        this._value.peerId = value;
        this.markDirty();
    }
    get peerType(): 'message' {
        return this._value.peerType;
    }
    set peerType(value: 'message') {
        this._checkIsWritable();
        if (value === this._value.peerType) { return; }
        this._value.peerType = value;
        this.markDirty();
    }
    get parentCommentId(): number | null {
        let res = this._value.parentCommentId;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set parentCommentId(value: number | null) {
        this._checkIsWritable();
        if (value === this._value.parentCommentId) { return; }
        this._value.parentCommentId = value;
        this.markDirty();
    }
    get uid(): number {
        return this._value.uid;
    }
    set uid(value: number) {
        this._checkIsWritable();
        if (value === this._value.uid) { return; }
        this._value.uid = value;
        this.markDirty();
    }
    get text(): string | null {
        let res = this._value.text;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set text(value: string | null) {
        this._checkIsWritable();
        if (value === this._value.text) { return; }
        this._value.text = value;
        this.markDirty();
    }
    get reactions(): ({ userId: number, reaction: string, })[] | null {
        let res = this._value.reactions;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set reactions(value: ({ userId: number, reaction: string, })[] | null) {
        this._checkIsWritable();
        if (value === this._value.reactions) { return; }
        this._value.reactions = value;
        this.markDirty();
    }
    get spans(): ({ type: 'user_mention', offset: number, length: number, user: number, } | { type: 'multi_user_mention', offset: number, length: number, users: (number)[], } | { type: 'room_mention', offset: number, length: number, room: number, } | { type: 'link', offset: number, length: number, url: string, } | { type: 'bold_text', offset: number, length: number, } | { type: 'italic_text', offset: number, length: number, } | { type: 'irony_text', offset: number, length: number, } | { type: 'inline_code_text', offset: number, length: number, } | { type: 'code_block_text', offset: number, length: number, } | { type: 'insane_text', offset: number, length: number, } | { type: 'loud_text', offset: number, length: number, } | { type: 'rotating_text', offset: number, length: number, } | { type: 'date_text', offset: number, length: number, date: number, } | { type: 'all_mention', offset: number, length: number, })[] | null {
        let res = this._value.spans;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set spans(value: ({ type: 'user_mention', offset: number, length: number, user: number, } | { type: 'multi_user_mention', offset: number, length: number, users: (number)[], } | { type: 'room_mention', offset: number, length: number, room: number, } | { type: 'link', offset: number, length: number, url: string, } | { type: 'bold_text', offset: number, length: number, } | { type: 'italic_text', offset: number, length: number, } | { type: 'irony_text', offset: number, length: number, } | { type: 'inline_code_text', offset: number, length: number, } | { type: 'code_block_text', offset: number, length: number, } | { type: 'insane_text', offset: number, length: number, } | { type: 'loud_text', offset: number, length: number, } | { type: 'rotating_text', offset: number, length: number, } | { type: 'date_text', offset: number, length: number, date: number, } | { type: 'all_mention', offset: number, length: number, })[] | null) {
        this._checkIsWritable();
        if (value === this._value.spans) { return; }
        this._value.spans = value;
        this.markDirty();
    }
    get attachments(): ({ type: 'file_attachment', fileId: string, filePreview: string | null, fileMetadata: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, id: string, } | { type: 'rich_attachment', title: string | null, subTitle: string | null, titleLink: string | null, text: string | null, icon: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, image: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, iconInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, imageInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, titleLinkHostname: string | null, keyboard: { buttons: (({ title: string, style: 'DEFAULT' | 'LIGHT', url: string | null, })[])[], } | null, id: string, })[] | null {
        let res = this._value.attachments;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set attachments(value: ({ type: 'file_attachment', fileId: string, filePreview: string | null, fileMetadata: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, id: string, } | { type: 'rich_attachment', title: string | null, subTitle: string | null, titleLink: string | null, text: string | null, icon: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, image: { uuid: string, crop: { x: number, y: number, w: number, h: number, } | null, } | null, iconInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, imageInfo: { isImage: boolean, isStored: boolean, imageWidth: number | null, imageHeight: number | null, imageFormat: string | null, mimeType: string, name: string, size: number, } | null, titleLinkHostname: string | null, keyboard: { buttons: (({ title: string, style: 'DEFAULT' | 'LIGHT', url: string | null, })[])[], } | null, id: string, })[] | null) {
        this._checkIsWritable();
        if (value === this._value.attachments) { return; }
        this._value.attachments = value;
        this.markDirty();
    }
    get deleted(): boolean | null {
        let res = this._value.deleted;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set deleted(value: boolean | null) {
        this._checkIsWritable();
        if (value === this._value.deleted) { return; }
        this._value.deleted = value;
        this.markDirty();
    }
    get edited(): boolean | null {
        let res = this._value.edited;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set edited(value: boolean | null) {
        this._checkIsWritable();
        if (value === this._value.edited) { return; }
        this._value.edited = value;
        this.markDirty();
    }
    get visible(): boolean | null {
        let res = this._value.visible;
        if (res !== null && res !== undefined) { return res; }
        return null;
    }
    set visible(value: boolean | null) {
        this._checkIsWritable();
        if (value === this._value.visible) { return; }
        this._value.visible = value;
        this.markDirty();
    }
}

export class CommentFactory extends FEntityFactory<Comment> {
    static schema: FEntitySchema = {
        name: 'Comment',
        editable: false,
        primaryKeys: [
            { name: 'id', type: 'number' },
        ],
        fields: [
            { name: 'peerId', type: 'number' },
            { name: 'peerType', type: 'enum', enumValues: ['message'] },
            { name: 'parentCommentId', type: 'number' },
            { name: 'uid', type: 'number' },
            { name: 'text', type: 'string', secure: true },
            { name: 'reactions', type: 'json' },
            { name: 'spans', type: 'json' },
            { name: 'attachments', type: 'json' },
            { name: 'deleted', type: 'boolean' },
            { name: 'edited', type: 'boolean' },
            { name: 'visible', type: 'boolean' },
        ],
        indexes: [
            { name: 'peer', type: 'range', fields: ['peerType', 'peerId', 'id'] },
            { name: 'child', type: 'range', fields: ['parentCommentId', 'id'] },
        ],
    };

    static async create(layer: EntityLayer) {
        let directory = await layer.resolveEntityDirectory('comment');
        let config = { enableVersioning: true, enableTimestamps: true, validator: CommentFactory.validate, keyValidator: CommentFactory.validateKey, hasLiveStreams: false };
        let indexPeer = new FEntityIndex(await layer.resolveEntityIndexDirectory('comment', 'peer'), 'peer', ['peerType', 'peerId', 'id'], false);
        let indexChild = new FEntityIndex(await layer.resolveEntityIndexDirectory('comment', 'child'), 'child', ['parentCommentId', 'id'], false);
        let indexes = {
            peer: indexPeer,
            child: indexChild,
        };
        return new CommentFactory(layer, directory, config, indexes);
    }

    readonly indexPeer: FEntityIndex;
    readonly indexChild: FEntityIndex;

    private static validate(src: any) {
        validators.notNull('id', src.id);
        validators.isNumber('id', src.id);
        validators.notNull('peerId', src.peerId);
        validators.isNumber('peerId', src.peerId);
        validators.notNull('peerType', src.peerType);
        validators.isEnum('peerType', src.peerType, ['message']);
        validators.isNumber('parentCommentId', src.parentCommentId);
        validators.notNull('uid', src.uid);
        validators.isNumber('uid', src.uid);
        validators.isString('text', src.text);
        validators.isJson('reactions', src.reactions, jVec(json(() => {
            jField('userId', jNumber());
            jField('reaction', jString());
        })));
        validators.isJson('spans', src.spans, jVec(jEnum(
            json(() => {
                jField('type', jString('user_mention'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('user', jNumber());
            }), 
            json(() => {
                jField('type', jString('multi_user_mention'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('users', jVec(jNumber()));
            }), 
            json(() => {
                jField('type', jString('room_mention'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('room', jNumber());
            }), 
            json(() => {
                jField('type', jString('link'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('url', jString());
            }), 
            json(() => {
                jField('type', jString('bold_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('italic_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('irony_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('inline_code_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('code_block_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('insane_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('loud_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('rotating_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
            }), 
            json(() => {
                jField('type', jString('date_text'));
                jField('offset', jNumber());
                jField('length', jNumber());
                jField('date', jNumber());
            }), 
            json(() => {
                jField('type', jString('all_mention'));
                jField('offset', jNumber());
                jField('length', jNumber());
            })
        )));
        validators.isJson('attachments', src.attachments, jVec(jEnum(
            json(() => {
                jField('type', jString('file_attachment'));
                jField('fileId', jString());
                jField('filePreview', jString()).nullable();
                jField('fileMetadata', json(() => {
                jField('isImage', jBool());
                jField('isStored', jBool());
                jField('imageWidth', jNumber()).nullable();
                jField('imageHeight', jNumber()).nullable();
                jField('imageFormat', jString()).nullable();
                jField('mimeType', jString());
                jField('name', jString());
                jField('size', jNumber());
            })).nullable();
                jField('id', jString());
            }), 
            json(() => {
                jField('type', jString('rich_attachment'));
                jField('title', jString()).nullable();
                jField('subTitle', jString()).nullable();
                jField('titleLink', jString()).nullable();
                jField('text', jString()).nullable();
                jField('icon', json(() => {
                jField('uuid', jString());
                jField('crop', json(() => {
                jField('x', jNumber());
                jField('y', jNumber());
                jField('w', jNumber());
                jField('h', jNumber());
            })).nullable();
            })).nullable();
                jField('image', json(() => {
                jField('uuid', jString());
                jField('crop', json(() => {
                jField('x', jNumber());
                jField('y', jNumber());
                jField('w', jNumber());
                jField('h', jNumber());
            })).nullable();
            })).nullable();
                jField('iconInfo', json(() => {
                jField('isImage', jBool());
                jField('isStored', jBool());
                jField('imageWidth', jNumber()).nullable();
                jField('imageHeight', jNumber()).nullable();
                jField('imageFormat', jString()).nullable();
                jField('mimeType', jString());
                jField('name', jString());
                jField('size', jNumber());
            })).nullable();
                jField('imageInfo', json(() => {
                jField('isImage', jBool());
                jField('isStored', jBool());
                jField('imageWidth', jNumber()).nullable();
                jField('imageHeight', jNumber()).nullable();
                jField('imageFormat', jString()).nullable();
                jField('mimeType', jString());
                jField('name', jString());
                jField('size', jNumber());
            })).nullable();
                jField('titleLinkHostname', jString()).nullable();
                jField('keyboard', json(() => {
                jField('buttons', jVec(jVec(json(() => {
                jField('title', jString());
                jField('style', jEnumString('DEFAULT', 'LIGHT'));
                jField('url', jString()).nullable();
            }))));
            })).nullable();
                jField('id', jString());
            })
        )));
        validators.isBoolean('deleted', src.deleted);
        validators.isBoolean('edited', src.edited);
        validators.isBoolean('visible', src.visible);
    }

    private static validateKey(key: Tuple[]) {
        validators.isNumber('0', key[0]);
    }

    constructor(layer: EntityLayer, directory: Subspace, config: FEntityOptions, indexes: { peer: FEntityIndex, child: FEntityIndex }) {
        super('Comment', 'comment', config, [indexes.peer, indexes.child], layer, directory);
        this.indexPeer = indexes.peer;
        this.indexChild = indexes.child;
    }
    extractId(rawId: any[]) {
        if (rawId.length !== 1) { throw Error('Invalid key length!'); }
        return { 'id': rawId[0] };
    }
    async findById(ctx: Context, id: number) {
        return await this._findById(ctx, [id]);
    }
    async create(ctx: Context, id: number, shape: CommentShape) {
        return await this._create(ctx, [id], { id, ...shape });
    }
    async create_UNSAFE(ctx: Context, id: number, shape: CommentShape) {
        return await this._create_UNSAFE(ctx, [id], { id, ...shape });
    }
    watch(ctx: Context, id: number) {
        return this._watch(ctx, [id]);
    }
    async allFromPeerAfter(ctx: Context, peerType: 'message', peerId: number, after: number) {
        return await this._findRangeAllAfter(ctx, this.indexPeer.directory, [peerType, peerId], after);
    }
    async rangeFromPeerAfter(ctx: Context, peerType: 'message', peerId: number, after: number, limit: number, reversed?: boolean) {
        return await this._findRangeAfter(ctx, this.indexPeer.directory, [peerType, peerId], after, limit, reversed);
    }
    async rangeFromPeer(ctx: Context, peerType: 'message', peerId: number, limit: number, reversed?: boolean) {
        return await this._findRange(ctx, this.indexPeer.directory, [peerType, peerId], limit, reversed);
    }
    async rangeFromPeerWithCursor(ctx: Context, peerType: 'message', peerId: number, limit: number, after?: string, reversed?: boolean) {
        return await this._findRangeWithCursor(ctx, this.indexPeer.directory, [peerType, peerId], limit, after, reversed);
    }
    async allFromPeer(ctx: Context, peerType: 'message', peerId: number) {
        return await this._findAll(ctx, this.indexPeer.directory, [peerType, peerId]);
    }
    createPeerStream(peerType: 'message', peerId: number, limit: number, after?: string) {
        return this._createStream(this.indexPeer.directory, [peerType, peerId], limit, after); 
    }
    async allFromChildAfter(ctx: Context, parentCommentId: number, after: number) {
        return await this._findRangeAllAfter(ctx, this.indexChild.directory, [parentCommentId], after);
    }
    async rangeFromChildAfter(ctx: Context, parentCommentId: number, after: number, limit: number, reversed?: boolean) {
        return await this._findRangeAfter(ctx, this.indexChild.directory, [parentCommentId], after, limit, reversed);
    }
    async rangeFromChild(ctx: Context, parentCommentId: number, limit: number, reversed?: boolean) {
        return await this._findRange(ctx, this.indexChild.directory, [parentCommentId], limit, reversed);
    }
    async rangeFromChildWithCursor(ctx: Context, parentCommentId: number, limit: number, after?: string, reversed?: boolean) {
        return await this._findRangeWithCursor(ctx, this.indexChild.directory, [parentCommentId], limit, after, reversed);
    }
    async allFromChild(ctx: Context, parentCommentId: number) {
        return await this._findAll(ctx, this.indexChild.directory, [parentCommentId]);
    }
    createChildStream(parentCommentId: number, limit: number, after?: string) {
        return this._createStream(this.indexChild.directory, [parentCommentId], limit, after); 
    }
    protected _createEntity(ctx: Context, value: any, isNew: boolean) {
        return new Comment(ctx, this.layer, this.directory, [value.id], value, this.options, isNew, this.indexes, 'Comment');
    }
}

export interface AllEntities {
    readonly layer: EntityLayer;
    readonly allEntities: FEntityFactory<FEntity>[];
    readonly Message: MessageFactory;
    readonly Comment: CommentFactory;
}
export class AllEntitiesDirect extends EntitiesBase implements AllEntities {
    static readonly schema: FEntitySchema[] = [
        MessageFactory.schema,
        CommentFactory.schema,
    ];

    static async create(layer: EntityLayer) {
        let allEntities: FEntityFactory<FEntity>[] = [];
        let MessagePromise = MessageFactory.create(layer);
        let CommentPromise = CommentFactory.create(layer);
        allEntities.push(await MessagePromise);
        allEntities.push(await CommentPromise);
        let entities = {
            layer, allEntities,
            Message: await MessagePromise,
            Comment: await CommentPromise,
        };
        return new AllEntitiesDirect(entities);
    }

    readonly allEntities: FEntityFactory<FEntity>[] = [];
    readonly Message: MessageFactory;
    readonly Comment: CommentFactory;

    private constructor(entities: AllEntities) {
        super(entities.layer);
        this.Message = entities.Message;
        this.allEntities.push(this.Message);
        this.Comment = entities.Comment;
        this.allEntities.push(this.Comment);
    }
}
